notifications:
  recipients:
#    - foobar@example.com
language: cpp
compiler:
  - gcc
  - clang
install:
  - curl https://raw.github.com/clear-code/cutter/master/data/travis/setup.sh | sh
  - sudo apt-get install -qq -y autotools-dev libglib2.0-dev libjson-glib-dev libsoup2.4-dev libmysqlclient-dev sqlite3 ndoutils-nagios3-mysql
  - mysql -u root -e "GRANT all on ndoutils.* TO ndoutils@localhost IDENTIFIED BY 'admin';"
before_script:
  - ./autogen.sh
  - ./configure
  - sudo chmod +w /run
script:
  - ./server/mlpl/test/run-test.sh
  - cd server/test && ./run-test.sh
